---
title: "Codebook"
author: "A student"
date: "06/11/2021"
output: word_document
---



#This is a code book for week 4 project
R scrip includes following steps:

1. Download the data
2. unzip the data

About the data set:

The source data are from the Human Activity Recognition Using Smartphones Data Set. 

About the script:

1. Read the files and merging the training data set and testing data set to create on data set
  (1) reading features.txt: List of all features 
 
  (2) read subject_train.txt: ID for training subjects being observed
  
  (3) read subject_test.txt: ID for  testing subjects being observed
  
  (4) read X_train.txt: Training set.
  
  (5) read Y_train.txt: Training labels
  
  (6) read X_test.txt:  Test set.
  (7) read Y_test.txt: Test labels
  (8) read activity_labels.txt: Links the class labels with their activity name.

2. combine subject id, activity code,  training set and testing set to create one data set.
3. Extract only the measurement on the mean and standard deviation for each measurement
4. Uses descriptive activity names to name the activities in the data set
5.Appropriately labels the data set with descriptive variable names: 
    (1) prefix t is replaced by Time
    (2) Acc is replaced by Accelerometer
    (3) Gyro is replaced by Gyroscope
    (4) prefix f is replaced by Frequency
    (5) Mag is replaced by Magnitude
    (6) BodyBody is replaced by Body
    (7) angle is placed by Angle
    
6.From the data set in step 5, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
 Export final tidy data set and called it "tidy_data.txt"

7.Variables:

a. Postion 1	Suject_id 	Unique identifier for 30 volunteers  
b. Position 2	Test_activity 	The activities include :
  1. WALKING
  2. WALKING_UPSTAIRS
  3. WALKING_DOWNSTAIRS
  4. SITTING
  5. STANDING
  6. LAYING

C. Postion 3-81	

                                     
 [3] "TimeBodyAccelerometer-mean()-X"                    
 [4] "TimeBodyAccelerometer-mean()-Y"                    
 [5] "TimeBodyAccelerometer-mean()-Z"                    
 [6] "TimeBodyAccelerometer-std()-X"                     
 [7] "TimeBodyAccelerometer-std()-Y"                     
 [8] "TimeBodyAccelerometer-std()-Z"                     
 [9] "TimeGravityAccelerometer-mean()-X"                 
[10] "TimeGravityAccelerometer-mean()-Y"                 
[11] "TimeGravityAccelerometer-mean()-Z"                 
[12] "TimeGravityAccelerometer-std()-X"                  
[13] "TimeGravityAccelerometer-std()-Y"                  
[14] "TimeGravityAccelerometer-std()-Z"                  
[15] "TimeBodyAccelerometerJerk-mean()-X"                
[16] "TimeBodyAccelerometerJerk-mean()-Y"                
[17] "TimeBodyAccelerometerJerk-mean()-Z"                
[18] "TimeBodyAccelerometerJerk-std()-X"                 
[19] "TimeBodyAccelerometerJerk-std()-Y"                 
[20] "TimeBodyAccelerometerJerk-std()-Z"                 
[21] "TimeBodyGyroscope-mean()-X"                        
[22] "TimeBodyGyroscope-mean()-Y"                        
[23] "TimeBodyGyroscope-mean()-Z"                        
[24] "TimeBodyGyroscope-std()-X"                         
[25] "TimeBodyGyroscope-std()-Y"                         
[26] "TimeBodyGyroscope-std()-Z"                         
[27] "TimeBodyGyroscopeJerk-mean()-X"                    
[28] "TimeBodyGyroscopeJerk-mean()-Y"                    
[29] "TimeBodyGyroscopeJerk-mean()-Z"                    
[30] "TimeBodyGyroscopeJerk-std()-X"                     
[31] "TimeBodyGyroscopeJerk-std()-Y"                     
[32] "TimeBodyGyroscopeJerk-std()-Z"                     
[33] "TimeBodyAccelerometerMagnitude-mean()"             
[34] "TimeBodyAccelerometerMagnitude-std()"              
[35] "TimeGravityAccelerometerMagnitude-mean()"          
[36] "TimeGravityAccelerometerMagnitude-std()"           
[37] "TimeBodyAccelerometerJerkMagnitude-mean()"         
[38] "TimeBodyAccelerometerJerkMagnitude-std()"          
[39] "TimeBodyGyroscopeMagnitude-mean()"                 
[40] "TimeBodyGyroscopeMagnitude-std()"                  
[41] "TimeBodyGyroscopeJerkMagnitude-mean()"             
[42] "TimeBodyGyroscopeJerkMagnitude-std()"              
[43] "FrequencyBodyAccelerometer-mean()-X"               
[44] "FrequencyBodyAccelerometer-mean()-Y"               
[45] "FrequencyBodyAccelerometer-mean()-Z"               
[46] "FrequencyBodyAccelerometer-std()-X"                
[47] "FrequencyBodyAccelerometer-std()-Y"                
[48] "FrequencyBodyAccelerometer-std()-Z"                
[49] "FrequencyBodyAccelerometer-meanFreq()-X"           
[50] "FrequencyBodyAccelerometer-meanFreq()-Y"           
[51] "FrequencyBodyAccelerometer-meanFreq()-Z"           
[52] "FrequencyBodyAccelerometerJerk-mean()-X"           
[53] "FrequencyBodyAccelerometerJerk-mean()-Y"           
[54] "FrequencyBodyAccelerometerJerk-mean()-Z"           
[55] "FrequencyBodyAccelerometerJerk-std()-X"            
[56] "FrequencyBodyAccelerometerJerk-std()-Y"            
[57] "FrequencyBodyAccelerometerJerk-std()-Z"            
[58] "FrequencyBodyAccelerometerJerk-meanFreq()-X"       
[59] "FrequencyBodyAccelerometerJerk-meanFreq()-Y"       
[60] "FrequencyBodyAccelerometerJerk-meanFreq()-Z"       
[61] "FrequencyBodyGyroscope-mean()-X"                   
[62] "FrequencyBodyGyroscope-mean()-Y"                   
[63] "FrequencyBodyGyroscope-mean()-Z"                   
[64] "FrequencyBodyGyroscope-std()-X"                    
[65] "FrequencyBodyGyroscope-std()-Y"                    
[66] "FrequencyBodyGyroscope-std()-Z"                    
[67] "FrequencyBodyGyroscope-meanFreq()-X"               
[68] "FrequencyBodyGyroscope-meanFreq()-Y"               
[69] "FrequencyBodyGyroscope-meanFreq()-Z"               
[70] "FrequencyBodyAccelerometerMagnitude-mean()"        
[71] "FrequencyBodyAccelerometerMagnitude-std()"         
[72] "FrequencyBodyAccelerometerMagnitude-meanFreq()"    
[73] "FrequencyBodyAccelerometerJerkMagnitude-mean()"    
[74] "FrequencyBodyAccelerometerJerkMagnitude-std()"     
[75] "FrequencyBodyAccelerometerJerkMagnitude-meanFreq()"
[76] "FrequencyBodyGyroscopeMagnitude-mean()"            
[77] "FrequencyBodyGyroscopeMagnitude-std()"             
[78] "FrequencyBodyGyroscopeMagnitude-meanFreq()"        
[79] "FrequencyBodyGyroscopeJerkMagnitude-mean()"        
[80] "FrequencyBodyGyroscopeJerkMagnitude-std()"         
[81] "FrequencyBodyGyroscopeJerkMagnitude-meanFreq()"    

These variables include measurements on the mean and standard deviation for each measurement. 

Body: signal based on the body of a participant

Mean indicates the measurement is a mean

Std indicates standard deviation



X means measurement is taken along the x dimension

y means measurement is taken along the y dimension

Z means measurement is taken along the Z dimension




